export const safetyAreas = [
  {
    id: "youtubeHor",
    title: "YouTube Horizontal",
    overlay: {
      top: "3.7%",
      left: "2.5%",
      right: "8.9%",
      style: "solid",
      color: "#FF0000",
      fontColor: "#ffffff",
      zIndex: 10,
      labelPosition: "bottom",
    },
    aspectRatio: "16:9",
    imgSrc: "YouTube_Horizontal_safe_zone.svg",
  },
  {
    id: "youtubeVer",
    title: "YouTube Vertical",
    overlay: {
      top: "15%",
      left: "4.4%",
      right: "17.7%",
      style: "solid",
      color: "#FF0000",
      fontColor: "#ffffff",
      zIndex: 60,
      labelPosition: "bottom",
    },
    aspectRatio: "9:16",
    imgSrc: "YouTube_Vertical_Video_Safe_Zone.svg",
  },
  {
    id: "instagramFbStories",
    title: "Instagram / FB Stories",
    overlay: {
      top: "14%",
      left: "6%",
      right: "6%",
      style: "solid",
      color: "#E73372",
      fontColor: "#ffffff",
      zIndex: 60,
      labelPosition: "bottom",
    },
    aspectRatio: "9:16",
    imgSrc: "InstaStories_Vertical_Video_Safe_Zone.svg",
  },
  {
    id: "instagramFbReels",
    title: "Instagram / FB Reels",
    overlay: {
      top: "14%",
      left: "6%",
      right: "6%",
      style: "solid",
      color: "#E73372",
      fontColor: "#ffffff",
      zIndex: 50,
      labelPosition: "bottom",
    },
    aspectRatio: "9:16",
    imgSrc: "InstaReels_Vertical_Video_Safe_Zone.svg",
  },
  {
    id: "tiktok",
    title: "TikTok - In feed standard",
    overlay: {
      top: "13.3%",
      left: "11.6%",
      right: "11.2%",
      style: "solid",
      color: "#FC3663",
      fontColor: "#ffffff",
      zIndex: 40,
      labelPosition: "top",
    },
    aspectRatio: "9:16",
    imgSrc: "TikTok_vertical_safe_zone.svg",
  },
  {
    id: "snapchat",
    title: "Snapchat - Stories ads",
    overlay: {
      top: "8%",
      left: "5.3%",
      right: "5.7%",
      style: "solid",
      color: "#FFFA37",
      fontColor: "#000000",
      zIndex: 30,
      labelPosition: "bottom",
    },
    aspectRatio: "9:16",
    imgSrc: "Snapchat_Vertical_Video_Safe_Zone.svg",
  },
  {
    id: "snapchatUnified",
    title: "Snapchat - Unified",
    overlay: {
      top: "10.3%",
      left: "5.7%",
      right: "5.7%",
      style: "solid",
      color: "#FFFA37",
      fontColor: "#000000",
      zIndex: 30,
      labelPosition: "bottom",
    },
    aspectRatio: "9:16",
    imgSrc: "Snapchat_Vertical_Video_Safe_zone_new.svg",
  },
];
